# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="resources.resource")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resource_likes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="resourcelike",
            constraint=models.UniqueConstraint(fields=("resource", "user"), name="unique_resource_like"),
        ),
    ]
